import "@/styles/globals.css";
import { Suspense } from "react";
import Header from "@/components/Header";
import Providers from "@/components/Providers";
import Loading from "./loading";

export const metadata = {
  title: "Live news app",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-100 dark:bg-zinc-900 transition-all duration-700 ease-out">
        <Providers>
          <Header />
          <Suspense fallback={<Loading />}>
            <div className="max-w-6xl mx-auto">{children}</div>
          </Suspense>
        </Providers>
      </body>
    </html>
  );
}
